### ISSUE TITLE
Abstract space hierarchy

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/CityGML-3.0CM#13] opened 2018-09-09 17:21 UTC
Most of the Abstract space hierarchy is not necessary if you just want to do the things you did with CityGML 2.0. The “AbstractPhysicSpace” / “AbstractOccupiedSpace”  is more or less the same as the CityObject in CityGML 2.0.  I do not see a big advantage for those users (such as ADV in Germany, sveral million buildings in LoD1 and 2). 
It looks like the Abstract space hierarchy is mainly introduced to model “AbstractVoid” – this is useful in some applications, but couldn’t it be modeled as a separate module? 

It would be good if the "space concept" does not have such a big impact on the core, but will be modeled as a separate module. So people can make use of it if they have the need.

**Comment by volkercoors** [comment] 2018-09-09 17:23
In general, I doubt that “void” is a CityOject, but this is more a philosophical question – Chris Gold says in his book on Spatial context that void or empty space does not exist

**Comment by volkercoors** [comment] 2018-09-09 17:50
to illustrate the issue:

![grafik](https://user-images.githubusercontent.com/5288711/45267208-7c4fc080-b468-11e8-9aac-8757f48018a1.png)

AbstractVoid is an AbstractUnoccupiedSpace is an AbstractPhysicalSpace is an AbstractSpace is an AbstractCityObject. Why is this necessary? AbstractPhysicalSpace and AbstractUnoccupiedSpace do not have Attributes, so it is just a new name. AbstractUnoccupiedSpace inherits occupancyDaytime and occupancyNighttime from AbstractSPace. Why? Isn't it UnoccupiedSpace?

In a data exchange format, all these Abstract classes will never appear. But if I want to generate Java Code out of it, I will end up with many Abstract classes or Interfaces that does not improve the readabilty of the code ("Matrjoschka" style) and I do not understand the benefits.

**Comment by 3DXScape** [comment] 2018-11-12 01:58
What is the argument for this degree of nesting? Symmetry? Structural consistency? I think there is one.

**Comment by TatjanaKutzner** [comment] 2019-03-28 16:47
In the web conference on 28 March 2019 we agreed that the issue has become obsolete, because Void does not exist any more (see issue #22) and also because of the discussion in issue #7.

Regarding the attributes occupancyDaytime and occupancyNighttime we discussed that the attributes are very application-specific and defined too high in the generalisation hierarchy.
We agreed on proposing an alternative modelling as part of the Construction and Transportation modules. In addition, we will define occupancy as qualified attribute, in this way various occupancies can be defined (e.g. morning, afternoon, weekend).

**Comment by TatjanaKutzner** [comment] 2019-04-24 16:12
The issue is closed as no further discussion on this issue took place after the web conference. 

The discussion on occupancy is moved to the new issue #62.

**Closed as completed by TatjanaKutzner** 2019-04-24 16:12 UTC
