### ISSUE TITLE
AbstractTopLevelCityObject

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/CityGML-3.0CM#32] opened 2018-10-10 18:37 UTC
user requirement to be solved (as far as I know):
better support to query all top level objects in CityGML  

proposed solution:
introduce an abstract class "AbstractTopLevelCityObject". All "top level" city objects inherit from this class

problem: 
this will introduce multiple inheritence 

my proposal:

Basically, all City objects have a tree structure. The "AbstractTopLevelCityObject" is the root of the tree. I doubt that it is necessary to model the root node of a tree like this. All elements of the tree are nodes, done. The node that has no predecessor is the root. I do not need to typify that via inheritance. If the root node has to be marked, this can also be done via an attribute:

Boolean isRoot (Yes / no) or boolean isTopLevelObject.

And BuildingPart can not be a root node anyway, as cardinality means that it has to be assigned to exactly one building. See discussion on issue #31  Building/BuildingPart.

Summary:
Delete the AbstractTopLevelCityObjects class without replacement. If there is a use case that requires  TopLevelCityObjects, then use an attribute in AbstractCityObject to mark whether or not an object is TopLevelObject (constant). Thus, the multiple inheritance in Building is resolve. Bride and other modules can use the same approach.

**Comment by volkercoors** [comment] 2018-10-10 18:38
![issue abstracttoplevelcityobject](https://user-images.githubusercontent.com/5288711/46758140-5ff3ad80-cccc-11e8-9589-758c972aab7c.png)

**Comment by clausnagel** [comment] 2018-10-10 19:27
The CityGML 2.0 conceptual model implicitly provides top-level feature types such as Building that can be decomposed into sub-feature types or components such as WallSurface, Room, or Window. In the GML encoding, the property element &lt;cityObjectMember&gt; of &lt;CityModel&gt; can however not just contain top-level features but also sub-features. For instance, the following is perfectly valid:

```
<core:CityModel>
  <core:cityObjectMember>
    <bldg:Window> ... </bldg:Window>
  </core:cityObjectMember>
</core:CityModel>
```
This might cause issues if your software expects to process buildings and not just single windows. For example, assume a database software that first must insert a tuple into a BUILDING table before inserting a tuple into the WINDOW table because of foreign key constraints. 

The AbstractTopLevelCityObject class in the current 3.0 draft is a proposal to make the distinction between top-level feature types and sub-feature types explicit in the conceptual model. And note that CityModel may only take AbstractTopLevelCityObject instances as cityObjectMember (this part is missing in your figure). So you would not be allowed to exchange a &lt;Window&gt; as &lt;cityObjectMember&gt; in the GML encoding anymore as it would violate the schema.

That being said, I nevertheless agree that we should try and avoid multiple inheritance in the conceptual model. Your proposal is one possible solution. However, I would rather see that the distinction between top-level feature types and sub-feature types should be made in the conceptual model and not on the level of the instances. Because if you introduce a constant attribute for every feature then this property also has to appear in every data instance document. For instance, every &lt;Building&gt; would have to carry a &lt;isTopLevelObject&gt;true&lt;isTopLevelObject&gt; property. This would also affect file size.

My proposal is therefore to introduce a new stereotype called &lt;&lt;TopLevelFeatureType&gt;&gt; that can be applied to feature type classes to mark them as top-level. So, for example, the Building class would be marked as &lt;&lt;TopLevelFeatureType&gt;&gt;, but the Window class would not. Then AbstractTopLevelCityObject can be skipped to avoid multiple inheritance but without loosing expressivity. Another benefit is that the stereotype &lt;&lt;TopLevelFeatureType&gt;&gt; could also be used when modelling ADEs.

However, note that in both cases, the current restriction on cityObjectMember would be lost. But if we  think that this restriction is required, then we could also think about introducing a conformance requirement.

**Comment by hlg** [comment] 2018-10-12 01:49
Duplicate of #9

**Comment by volkercoors** [comment] 2018-10-12 06:47
Stereotype looks like a good solution. And it will fix two issues. I support Claus proposal.

**Comment by 3DXScape** [comment] 2018-10-13 17:31
I started with a different opinion but when I wrote out my logic, I ended up in agreement with both Volker's goal and Claus' suggestion! ...steve
 
0. Multiple inheritance is only bad when there are multiple ways to inherit the same thing. Avoiding multiple inheritance avoids the *possibility* to have that problem. A rule against super-class inheritance clashes also works.
1. A stereotype used this way is going to be functionally equivalent to inheritance from a corresponding abstract class: an additional property will be added in an implementation to indicate "top-level-ness".  So behind the scenes, implementations where a class has both a stereotype and an abstract superclass will still ave a limited form of multiple inheritance. The UML rules limiting classes to at most a single stereotype and multiple stereotypes from having the same name effectively prevents clashes between stereotypes and, except possibly in the most contrived instances, clashes between stereotypes and super-classes..
2. It is possible and a good idea to make the distinction at the schema level because every instance will have elements that are unambiguously top level - i.e. something is gained and nothing is lost.
3. Claus' suggestion is a good way to achieve Volker's goal.

**Comment by 3DXScape** [comment] 2018-11-12 01:26
Is there any objection to Claus' modification of Volker's proposal? I see two other technical possibilities that avoid multiple inheritance:
1. A boolean property "isTopLevel" as also suggested by Volker.
2. An association (could be structured as an aggregation or composition) to model the set of top-level-objects.  
For me, any of these is OK, with a slight preference for the property (1.).

**Comment by hlg** [comment] 2018-11-12 02:19
@3DXScape: Option 2., isn't that exactly the `cityObjectMember` aggregation?

Otherwise I agree with @clausnagel's proposal. It is similar to what I head in mind in issue #9, where I suggested to make `AbstractTopLevelCityObject` the mixin class instead of mixing the main classes into it, in order to reduce the impact of multiple inheritance.

**Comment by 3DXScape** [comment] 2018-11-12 04:23
Yes. I was attempting to list several of the possible ways to do this. I think both your approach and Claus' suggestion are fine. Claus' suggestion eliminates the appearance of multiple inheritance without any loss of modelling power (depending on the _strictness property setting for the stereotype(s) if using EA).

**Comment by 3DXScape** [comment] 2018-11-30 05:17
Claus Nagel's proposal to use a <<TopLevelFeatureType>> stereotype appears to resolve this issue.

**Closed as completed by 3DXScape** 2018-11-30 05:17 UTC
