### ISSUE TITLE
Void vs. Opening

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#22] opened 2018-09-11 10:15 UTC
Is a Door a Void or an Opening? How are the terms Void and Opening defined? Can Void be considered a substractive element?

**Comment by hlg** [comment] 2018-09-12 07:03
Duplicate of #3

**Comment by 3DXScape** [comment] 2018-11-12 01:34
Have Door and Window (and maybe other things) been overloaded - may denote more than one concept and that is why the question arises?
Are subtractive elements good things/indispensable/helpful in our model??

**Comment by 3DXScape** [comment] 2018-12-01 01:13
Issue 3 closed as duplicate of this #22

**Comment by 3DXScape** [comment] 2018-12-01 01:15
hlg comment from #3
The UML document, page 14, says: "It needs to be discussed further within the SWG, whether a Door is a Void or an Opening." What is the difference between a void and an opening? I understand that there is a difference of whether doors and windows are treated as occupied spaces (constructive elements) within unoccupied spaces (openings) or as subtypes of unoccupied spaces (openings) within occupied spaces (e.g. walls). In IFC, openings and doors/windows are separate concepts: openings are "substractive features" that have a "voiding" relation with building elements such as walls or slabs and doors or windows are building elements which have a "filling" relation with the openings.

**Comment by clausnagel** [comment] 2018-12-18 09:02
Resolved in draft release [3.0.0-draft.2018.12.17.1](https://github.com/opengeospatial/CityGML-3.0CM/releases/tag/3.0.0-draft.2018.12.17.1)

**Comment by clausnagel** [comment] 2018-12-20 17:30
I think I closed this issue too quickly. [3.0.0-draft.2018.12.17.1](https://github.com/opengeospatial/CityGML-3.0CM/releases/tag/3.0.0-draft.2018.12.17.1) has made `Void` and `VoidSurface` concrete instead of abstract classes, and `Door` and `Window`  are now derived from `AbtractConstructiveElement` instead of `AbstractConstructionVoid`. But still the semantics of `Void` is not clear to me. Why and when would you model a `Void`? Can you provide a real-world example?

Is `Void` meant as substractive element which might be filled, for instance, by an opening similar to IFC? If so, I see a lot of issues with introducing such a concept. Please clarify.

**Comment by hlg** [comment] 2019-01-28 13:53
It seems that with 3.0.0-draft.2018.12.17.1 the `Void` and `VoidSurface` are now the only ways to model openings. There is no way to specify the relation between a wall and a door/window "in" this wall, or a wall surface and a door/window surface respectively. That would break backward compatibility, because the CityGML2 concept of an opening (in surfaces) does not exist anymore.

One way around the introduction of subtractive geometry could be to keep dedicated super classes for DoorSurface/WindowSurface and Door/Window, but just as a marker interface for such surfaces or constructive elements respectively, which are allowed to appear as openings, without inheriting from `AbstractUnoccupiedSpace`.

This would leave it up to the modeller to divide the volume of the opening hole between the geometries of the constructive opening element and the adjacent rooms. E.g. in a lower LOD you could model the door or window across the whole depth of the related wall, but in a higher LOD you may want to make the window/door thinner according to their actual depth, place it at a specific position inside the wall and possibly assign the bulk of the void volume to the adjacent rooms.

**Comment by TatjanaKutzner** [comment] 2019-03-13 09:46
In the web conference on 7 March 2019 we discussed that the original idea of the classes _Void_ and _VoidSurface_ was to allow for defining subtractive elements in CityGML. However, we do not intend to include explicit subtractive elements in CityGML. Also, the concepts are not further used in the model currently. Thus, we decided to remove the classes Void and VoidSurface.

To simplify the core model further, we discussed that it would make sense to remove the subclass _AbstractThematicSurface_ and, instead, to rename _AbstractSpaceBoundary_ to AbstractThematicSurface, with _ClosureSurface_ being its only subclass.

In addition, we will mark the association between AbstractSpace and AbstractThematicSurface as abstract, because the association is only implemented in the thematic modules.

**Closed as completed** 2019-04-04 09:37 UTC
