### ISSUE TITLE
Voids and related building elements (doors and windows)

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#3] opened 2018-07-30 12:01 UTC
The UML document, page 14, says: "It needs to be discussed further within the SWG, whether a Door is a Void or an Opening." What is the difference between a void and an opening? I understand that there is a difference of whether doors and windows are treated as occupied spaces (constructive elements) within unoccupied spaces (openings) or as subtypes of unoccupied spaces (openings) within occupied spaces (e.g. walls). In IFC, openings and doors/windows are separate concepts: openings are "substractive features" that have a "voiding" relation with building elements such as walls or slabs and doors or windows are building elements which have a "filling" relation with the openings.

**Comment by 3DXScape** [comment] 2018-12-01 01:12
Duplicate of #22

**Closed as completed by 3DXScape** 2018-12-01 01:12 UTC
